name=Pico_X
version=0.0.1
author=Teerawut Chitphomma <Teerawut.j@outlook.com>
maintainer=Teerawut Chitphomma <Teerawut.j@outlook.com>
sentence=A control library for Pico-x.
paragraph=This library easy to read input and control output on Pico-x 
category=Signal Input/Output
url=https://github.com
architectures=*
